### PR TITLE
fix string concatenation

### PR DESCRIPTION
**Pull request by arkonisus**

### CODE REVIEW

**Comment by jtsternberg** [comment]
Can you remove the `.DS_Store` from the commit?

**Comment by arkonisus** [comment]
Sry, i have to learn a lot ... ;)

**Comment by arkonisus** [comment]
Sry, by mistake i closed this request. I have to learn a lot ... :)

**Comment by jtsternberg** [comment]
Hmm now you removed the .gitignore file. No worries though, i'll clean this up and get it merged in.

**Comment by jtsternberg** [comment]
Ah, just realized we didn't have a .gitignore file. Thanks!

**Comment by arkonisus** [comment]
Ok, so it is hopefully all fine  ... it was my first PullRequst :)

**Comment by jtsternberg** [comment]
Yep, it's all good. Thanks for your contribution, and congrats on your first PR!

**Pull request merged**
