### PR TITLE
Widget snippet!

### PR DESCRIPTION
**Pull request by CarlosRios**
This needs a lot of work still. So far it creates a widget, registers some fields, and then outputs the fields in the widgets' form. I couldn't get saving to work properly, but I think we could definitely get it done.

A note on the saving issues. WP_Widget::update() saves every instance's data in a single option in the DB. The issue I had was passing that data back into CMB2 for each instance of the widget.

### CODE REVIEW

**Comment by jtsternberg** [comment]
Gonna check this out. BUT your PR looks insane. Is your branch up to date with master?

**Comment by jtsternberg** [comment]
Looks like the PR is crazy because trunk was behind. So nevermind. :)

**Comment by jtsternberg** [comment]
Thanks man. I revamped a bit and it now works for the most part, though any fields w/ JS barely work, if at all. https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/widgets/widget-example.php

Widget support probably needs some changes to CMB2 core, specifically a separate JS and CSS file for handling that usage.

**Comment by CarlosRios** [comment]
Dang! Sorry about the PR I was working in trunk.

I noticed that some of it would require changes to CMB2 core, but I was thinking it would be good to have something for now. The JS does bug out a bit when you add anything with the WP media uploader, but I found that if you add the widget and refresh the page it works just fine.

Your merge looks great by the way!

**Comment by jtsternberg** [comment]
Either way, it's good to have this handy, and provides a starting point for getting something in core some day. So, thank you for submitting!

**Pull request merged**
