### PR TITLE
Make Reverse an option

### PR DESCRIPTION
**Pull request by Ipstenu**
Add in a way to easily decide if you want the years reverse or not.

### CODE REVIEW

**Comment by jtsternberg** [comment]
This makes it so that both dropdowns are in the same order. Do you think that's easier to work with (better UX)? The existing way, it sorts the start from oldest to newest, and the finish from newest to oldest.

**Comment by Ipstenu** [comment]
It depends on the reasons for the range, I imagine... I know I'm adding shows, and most of them are going to be 'new' shows so going to 1930 and scrolling down (yes I know I can type in the year ;) ) is more of a pain than the other way.

Maybe make it option'd for the start and news->oldest for the finish? That feel slike it would suit most cases

**Comment by jtsternberg** [comment]
Yah, that'd be cool. The ability to choose for both fields would be ideal, with the default being what it is now.

**Comment by Ipstenu** [comment]
Maybe in 'default'  => array()?

start_date, start_direction, finish_date, finish_direction?

**Comment by jtsternberg** [comment]
I wouldn't do it in 'default' because that's intended strictly as a default value for the field. I've actually gone ahead and updated the field to use the proper field properties for the different parts. For example, using the text array for text changes, and options array for options. It's all demo-ed here: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/custom-field-types/year-range-field-type.php#L18-L37
(the 'split_values' I left as a primary argument to make it simpler for use in the sanitize callback)

So to introduce the sort-direction, I'd use the options parameter. So in the field config, something like:
```php
$cmb_demo->add_field( array(
	'name'     => __( 'Date Year Range', 'cmb2' ),
	'desc'     => __( 'field description (optional)', 'cmb2' ),
	'id'       => $prefix . 'date_year_range',
	'type'     => 'date_year_range',
	'options'  => array(
		// 'earliest' => 1970,
		'start_reverse_sort' => true,
		'finish_reverse_sort' => false,
	),
) );

```

And then in the field, can check like:

$start_reverse_sort = $field->options( 'start_reverse_sort' ) ? true : false;
$finish_reverse_sort = $field->options( 'finish_reverse_sort' ) ? true : false;

Also, with that last update I pushed, I messed up your PR being able to be merged. Sorry!

**Comment by Ipstenu** [comment]
Okay... It works now (though I think github decided my copy/edit was not using tabs ... something's drunk)

**Comment by jtsternberg** [comment]
💥 Thanks!

**Pull request merged**
