### PR TITLE
Update address-field-type.php

### PR DESCRIPTION
**Pull request by arnekeller**
filter missed the full field_type name

### CODE REVIEW

**Comment by jtsternberg** [comment]
That's not correct. The field-type name is `address`.

**Comment by arnekeller** [comment]
..okay I'm confused.

The example won't work for me unless using "cmb2_render_address_field" instead of "cmb2_render_address"

Isn't it the same as in the basic email example where we are calling: 
add_filter( 'cmb2_sanitize_text_email', 'cmb2_sanitize_text_email_callback', 10, 2 );
where text_email is the field_type. 
The explanation also states:

*This filter defines what code gets executed when the user attempts to save a value in a field type called text_email in the library. This first parameter, the hook name, must be cmb2_sanitize_ followed by the field type name.

What am I missing?

**Comment by jtsternberg** [comment]
Yes, `text_email` is the field-type name in that scenario, and this is the field registration array:
```php
array(
	'name' => 'Email',
	'desc' => 'Invalid email addresses will be wiped out.',
	'id'   => '_cmb2_person_email',
	'type' => 'text_email',
),
```

In the Address example, `address` is the field-type name, and the field registration array should look like:

```php
array(
	'name' => 'Address',
	'desc' => 'Custom Address Field',
	'id'   => '_cmb2_person_address',
	'type' => 'address',
),
```

**Comment by jtsternberg** [comment]
I just dropped the [address type plugin](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/custom-field-types/address-field-type.php) in a fresh install w/ CMB2, and used the `address` field registration above, and it works flawlessly.

**Comment by arnekeller** [comment]
Makes sense now. Due to the naming of the functions and the first example in mind I assumed:
```array(
  'name' => 'Somename',
  'id'   => '_cmb2_person_address',
  'type' => 'address_field',
)```

Which worked fine in my Implementation well... after altering the `add_filter` argument. ;)

Thanks for clearing that up

**Comment by jtsternberg** [comment]
To make it clearer, I've added the configuration to the wiki: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#setup-the-field

**Comment by arnekeller** [comment]
:+1:

**Pull request closed without merging**
